// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCQdiSF_zPiFHRQ0JfRPeQqPzrxoRUJfVY',
    appId: '1:85373941587:android:be2c9d4c7ab70466c293a6',
    messagingSenderId: '85373941587',
    projectId: 'vigo-billing',
    storageBucket: 'vigo-billing.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDeBowKNb12BGsmk0oSMbFg_6-RVXai_0Y',
    appId: '1:85373941587:ios:eaf1c5847b40441bc293a6',
    messagingSenderId: '85373941587',
    projectId: 'vigo-billing',
    storageBucket: 'vigo-billing.firebasestorage.app',
    iosBundleId: 'com.billing.vigo',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBKPO9IlcxMHb1hGU4YupmGEoYD_IGVPfM',
    appId: '1:85373941587:web:ce4ca23046facdd7c293a6',
    messagingSenderId: '85373941587',
    projectId: 'vigo-billing',
    authDomain: 'vigo-billing.firebaseapp.com',
    storageBucket: 'vigo-billing.firebasestorage.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDeBowKNb12BGsmk0oSMbFg_6-RVXai_0Y',
    appId: '1:85373941587:ios:eaf1c5847b40441bc293a6',
    messagingSenderId: '85373941587',
    projectId: 'vigo-billing',
    storageBucket: 'vigo-billing.firebasestorage.app',
    iosBundleId: 'com.billing.vigo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAdhlJhhiMPg5FPm_FZJjphYNdDH5LFgS0',
    appId: '1:85373941587:web:aa6e9f0b4d23b445c293a6',
    messagingSenderId: '85373941587',
    projectId: 'vigo-billing',
    authDomain: 'vigo-billing.firebaseapp.com',
    storageBucket: 'vigo-billing.firebasestorage.app',
  );

}